version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers

    steps:
      - deploy:
          production:
            branch: master
            commands:
              - npm run update
